- name: First Playbook
  hosts: all 
  tasks:
    - name: Ping the ansible node
      ping:

    - name: Display hostname
      shell: hostname
      register: output

    - shell: adfsadf
      when: ansible_hostname == "ubuntu1"
      ignore_errors: yes

    - debug: var=output.stdout
