- name: Install nginx web server, configure it and deploy custom web page in it
  hosts: all
  tasks:
    - name: Install nginx in Ubuntu node
      apt:  name=nginx state=latest update_cache=yes

    - name: Install curl utility in Ubuntu node
      apt: name=curl state=latest

    - name: Check if you are able to access nginx web page
      shell: curl http://localhost:80
      register: curl_status
      ignore_errors: yes

    - debug: var=curl_status

    - name: Start the nginx server in Ubuntu node
      when: curl_status.failed == true
      shell: nginx

    - name: Create custom web root folder
      file: path=/var/html state=directory mode=0755

    - name: Configure nginx to pick html pages from our custom folder
      copy: src=default dest=/etc/nginx/sites-available/default

    - name: Deploy custom html page into nginx server
      copy: src=index.html dest=/var/html/index.html

    - name: Restart nginx serve to apply the config changes
      shell: nginx -s reload
