- name: Create the custom document root folder
  file: path=/var/html state=directory mode=0755
  tags:
    - CentOS
    - Ubuntu

- name: Deploy custom html page 
  template: src=index.html.j2 dest=/var/html/index.html
  tags:
    - CentOS
    - Ubuntu
